// Generated by Scripts/generate_design_tokens.py from docs/repsetforge-tokens.json.
// Do not edit by hand.

import SwiftUI

enum DesignTokens {
  enum ColorToken {
    static let surface = Color(light: Color(red: 247/255, green: 248/255, blue: 250/255, opacity: 1), dark: Color(red: 13/255, green: 15/255, blue: 18/255, opacity: 1))
    static let surfaceRaised = Color(light: Color(red: 255/255, green: 255/255, blue: 255/255, opacity: 1), dark: Color(red: 22/255, green: 25/255, blue: 30/255, opacity: 1))
    static let surfaceInput = Color(light: Color(red: 238/255, green: 240/255, blue: 244/255, opacity: 1), dark: Color(red: 29/255, green: 33/255, blue: 39/255, opacity: 1))
    static let hairline = Color(light: Color(red: 226/255, green: 229/255, blue: 234/255, opacity: 1), dark: Color(red: 38/255, green: 43/255, blue: 51/255, opacity: 1))
    static let textPrimary = Color(light: Color(red: 17/255, green: 20/255, blue: 24/255, opacity: 1), dark: Color(red: 242/255, green: 244/255, blue: 247/255, opacity: 1))
    static let textSecondary = Color(light: Color(red: 92/255, green: 101/255, blue: 114/255, opacity: 1), dark: Color(red: 139/255, green: 147/255, blue: 161/255, opacity: 1))
    static let textTertiary = Color(light: Color(red: 152/255, green: 160/255, blue: 172/255, opacity: 1), dark: Color(red: 90/255, green: 98/255, blue: 112/255, opacity: 1))
    static let signal = Color(light: Color(red: 31/255, green: 169/255, blue: 104/255, opacity: 1), dark: Color(red: 48/255, green: 229/255, blue: 133/255, opacity: 1))
    static let signalDim = Color(light: Color(red: 31/255, green: 169/255, blue: 104/255, opacity: 0.12), dark: Color(red: 48/255, green: 229/255, blue: 133/255, opacity: 0.14))
    static let onSignal = Color(light: Color(red: 255/255, green: 255/255, blue: 255/255, opacity: 1), dark: Color(red: 7/255, green: 19/255, blue: 12/255, opacity: 1))
    static let pr = Color(light: Color(red: 184/255, green: 134/255, blue: 11/255, opacity: 1), dark: Color(red: 245/255, green: 197/255, blue: 66/255, opacity: 1))
    static let prDim = Color(light: Color(red: 184/255, green: 134/255, blue: 11/255, opacity: 0.12), dark: Color(red: 245/255, green: 197/255, blue: 66/255, opacity: 0.14))
    static let warning = Color(light: Color(red: 217/255, green: 85/255, blue: 47/255, opacity: 1), dark: Color(red: 255/255, green: 122/255, blue: 89/255, opacity: 1))
    static let destructive = Color(light: Color(red: 217/255, green: 54/255, blue: 54/255, opacity: 1), dark: Color(red: 255/255, green: 93/255, blue: 93/255, opacity: 1))
  }

  enum Typography {
    static let largeTitle = TextStyle(size: 26, weight: .heavy, tracking: -0.03)
    static let title = TextStyle(size: 20, weight: .heavy, tracking: -0.02)
    static let heading = TextStyle(size: 15, weight: .heavy, tracking: 0)
    static let body = TextStyle(size: 14, weight: .semibold, tracking: 0)
    static let secondary = TextStyle(size: 12, weight: .medium, tracking: 0)
    static let eyebrow = TextStyle(size: 10, weight: .bold, tracking: 0.1)
    static let numericLarge = TextStyle(size: 20, weight: .semibold, tracking: 0)
    static let numericRow = TextStyle(size: 13, weight: .medium, tracking: 0)
  }

  enum Spacing {
    static let base: CGFloat = 4
    static let screenGutter: CGFloat = 10
    static let cardPadding: CGFloat = 10
    static let cardGap: CGFloat = 8
    static let setRowHeightVisual: CGFloat = 36
    static let setRowHitTarget: CGFloat = 44
    static let step1: CGFloat = 4
    static let step2: CGFloat = 8
    static let step3: CGFloat = 12
    static let step4: CGFloat = 16
    static let step5: CGFloat = 24
    static let step6: CGFloat = 32
  }

  enum Radius {
    static let card: CGFloat = 10
    static let input: CGFloat = 8
    static let pill: CGFloat = 22
    static let checkbox: CGFloat = 8
    static let segment: CGFloat = 9
    static let phoneSheet: CGFloat = 34
  }

  enum Motion {
    static let setCompleteDuration: TimeInterval = 0.25
    static let stateChangeDuration: TimeInterval = 0.2
  }
}

extension Color {
  init(light: Color, dark: Color) {
    self.init(uiColor: UIColor { traits in
      traits.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)
    })
  }
}

struct TextStyle {
  let size: CGFloat
  let weight: Font.Weight
  let tracking: CGFloat

  var font: Font {
    .system(size: size, weight: weight, design: .monospaced)
  }
}

extension View {
  func forgeTextStyle(_ style: TextStyle) -> some View {
    font(style.font)
      .tracking(style.tracking)
  }

  func forgeNumeric() -> some View {
    monospacedDigit()
  }
}
