import Foundation

/// Canonical catalog of every normal monster, organized in level bands.
/// To add a monster: append an entry here (with a sprite generated by
/// scripts/generate_pixel_assets.py) and it joins the spawn pool automatically.
enum RPGMonsterRegistry {

    static let all: [RPGMonster] = [
        // Levels 1–4
        RPGMonster(
            id: "training_slime", name: "Training Slime", family: "Slime",
            minLevel: 1, maxLevel: 4, rarity: .common,
            spriteAsset: "rpg_monster_training_slime", idleStyle: .bounce, attackStyle: .bounce,
            threat: 1, behaviorText: "Wobbles harmlessly, eager to be a warm-up."
        ),
        RPGMonster(
            id: "tiny_bat", name: "Tiny Bat", family: "Bat",
            minLevel: 1, maxLevel: 4, rarity: .uncommon,
            spriteAsset: "rpg_monster_tiny_bat", idleStyle: .hover, attackStyle: .hover,
            threat: 1, behaviorText: "Flutters in loops, more nuisance than threat."
        ),

        // Levels 5–9
        RPGMonster(
            id: "forest_slime", name: "Forest Slime", family: "Slime",
            minLevel: 5, maxLevel: 9, rarity: .common,
            spriteAsset: "rpg_monster_forest_slime", idleStyle: .bounce, attackStyle: .bounce,
            threat: 2, behaviorText: "A denser slime toughened by the wilds."
        ),
        RPGMonster(
            id: "cave_bat", name: "Cave Bat", family: "Bat",
            minLevel: 5, maxLevel: 9, rarity: .common,
            spriteAsset: "rpg_monster_cave_bat", idleStyle: .hover, attackStyle: .hover,
            threat: 2, behaviorText: "Screeches from the dark before diving."
        ),
        RPGMonster(
            id: "goblin_scout", name: "Goblin Scout", family: "Goblin",
            minLevel: 5, maxLevel: 9, rarity: .uncommon,
            spriteAsset: "rpg_monster_goblin_scout", idleStyle: .shamble, attackStyle: .shamble,
            threat: 3, behaviorText: "Probes for weakness with a rusty dagger."
        ),

        // Levels 10–14
        RPGMonster(
            id: "goblin_warrior", name: "Goblin Warrior", family: "Goblin",
            minLevel: 10, maxLevel: 14, rarity: .common,
            spriteAsset: "rpg_monster_goblin_warrior", idleStyle: .shamble, attackStyle: .shamble,
            threat: 4, behaviorText: "Swings a crude axe with real intent."
        ),
        RPGMonster(
            id: "bone_rat", name: "Bone Rat", family: "Undead",
            minLevel: 10, maxLevel: 14, rarity: .uncommon,
            spriteAsset: "rpg_monster_bone_rat", idleStyle: .shamble, attackStyle: .shamble,
            threat: 3, behaviorText: "Skitters on fleshless claws."
        ),
        RPGMonster(
            id: "wild_imp", name: "Wild Imp", family: "Demon",
            minLevel: 10, maxLevel: 14, rarity: .rare,
            spriteAsset: "rpg_monster_wild_imp", idleStyle: .bounce, attackStyle: .flicker,
            threat: 4, behaviorText: "Cackles and hurls sparks of chaos."
        ),

        // Levels 15–19
        RPGMonster(
            id: "skeleton_grunt", name: "Skeleton Grunt", family: "Undead",
            minLevel: 15, maxLevel: 19, rarity: .common,
            spriteAsset: "rpg_monster_skeleton_grunt", idleStyle: .shamble, attackStyle: .shamble,
            threat: 5, behaviorText: "Rattles forward, tireless and unblinking."
        ),
        RPGMonster(
            id: "orc_rookie", name: "Orc Rookie", family: "Orc",
            minLevel: 15, maxLevel: 19, rarity: .uncommon,
            spriteAsset: "rpg_monster_orc_rookie", idleStyle: .stomp, attackStyle: .stomp,
            threat: 5, behaviorText: "Green in every sense, but hits hard."
        ),
        RPGMonster(
            id: "cursed_mushroom", name: "Cursed Mushroom", family: "Plant",
            minLevel: 15, maxLevel: 19, rarity: .rare,
            spriteAsset: "rpg_monster_cursed_mushroom", idleStyle: .bounce, attackStyle: .flicker,
            threat: 5, behaviorText: "Puffs hexing spores when disturbed."
        ),

        // Levels 20–29
        RPGMonster(
            id: "orc_brute", name: "Orc Brute", family: "Orc",
            minLevel: 20, maxLevel: 29, rarity: .common,
            spriteAsset: "rpg_monster_orc_brute", idleStyle: .stomp, attackStyle: .stomp,
            threat: 6, behaviorText: "Drags a club the size of a doorframe."
        ),
        RPGMonster(
            id: "wraith", name: "Wraith", family: "Spirit",
            minLevel: 20, maxLevel: 29, rarity: .uncommon,
            spriteAsset: "rpg_monster_wraith", idleStyle: .hover, attackStyle: .flicker,
            threat: 6, behaviorText: "Drifts closer whenever you look away."
        ),
        RPGMonster(
            id: "stone_golem", name: "Stone Golem", family: "Golem",
            minLevel: 20, maxLevel: 29, rarity: .rare,
            spriteAsset: "rpg_monster_stone_golem", idleStyle: .stomp, attackStyle: .stomp,
            threat: 7, behaviorText: "Every step lands like a dropped barbell."
        ),

        // Levels 30–39
        RPGMonster(
            id: "armored_skeleton", name: "Armored Skeleton", family: "Undead",
            minLevel: 30, maxLevel: 39, rarity: .common,
            spriteAsset: "rpg_monster_armored_skeleton", idleStyle: .shamble, attackStyle: .shamble,
            threat: 7, behaviorText: "Old bones in older steel, still marching."
        ),
        RPGMonster(
            id: "fire_imp", name: "Fire Imp", family: "Demon",
            minLevel: 30, maxLevel: 39, rarity: .uncommon,
            spriteAsset: "rpg_monster_fire_imp", idleStyle: .bounce, attackStyle: .flicker,
            threat: 7, behaviorText: "Leaves scorch marks wherever it lands."
        ),
        RPGMonster(
            id: "hill_golem", name: "Hill Golem", family: "Golem",
            minLevel: 30, maxLevel: 39, rarity: .rare,
            spriteAsset: "rpg_monster_hill_golem", idleStyle: .stomp, attackStyle: .stomp,
            threat: 8, behaviorText: "Mistaken for terrain until it stands up."
        ),

        // Levels 40–49
        RPGMonster(
            id: "demon_knight", name: "Demon Knight", family: "Demon",
            minLevel: 40, maxLevel: 49, rarity: .common,
            spriteAsset: "rpg_monster_demon_knight", idleStyle: .shamble, attackStyle: .stomp,
            threat: 8, behaviorText: "A fallen champion sworn to darker reps."
        ),
        RPGMonster(
            id: "frost_wraith", name: "Frost Wraith", family: "Spirit",
            minLevel: 40, maxLevel: 49, rarity: .uncommon,
            spriteAsset: "rpg_monster_frost_wraith", idleStyle: .hover, attackStyle: .flicker,
            threat: 8, behaviorText: "The air crackles with cold around it."
        ),
        RPGMonster(
            id: "dragonling", name: "Dragonling", family: "Dragon",
            minLevel: 40, maxLevel: 49, rarity: .rare,
            spriteAsset: "rpg_monster_dragonling", idleStyle: .hover, attackStyle: .stomp,
            threat: 9, behaviorText: "Small for a dragon. Only for a dragon."
        ),

        // Levels 50+
        RPGMonster(
            id: "ancient_golem", name: "Ancient Golem", family: "Golem",
            minLevel: 50, maxLevel: nil, rarity: .common,
            spriteAsset: "rpg_monster_ancient_golem", idleStyle: .stomp, attackStyle: .stomp,
            threat: 9, behaviorText: "Runes older than the mountain still glow."
        ),
        RPGMonster(
            id: "abyss_wraith", name: "Abyss Wraith", family: "Spirit",
            minLevel: 50, maxLevel: nil, rarity: .uncommon,
            spriteAsset: "rpg_monster_abyss_wraith", idleStyle: .hover, attackStyle: .flicker,
            threat: 9, behaviorText: "It remembers every skipped workout."
        ),
        RPGMonster(
            id: "elder_dragonling", name: "Elder Dragonling", family: "Dragon",
            minLevel: 50, maxLevel: nil, rarity: .rare,
            spriteAsset: "rpg_monster_elder_dragonling", idleStyle: .hover, attackStyle: .stomp,
            threat: 10, behaviorText: "Gold-scaled and thoroughly unimpressed."
        ),
        RPGMonster(
            id: "infernal_beast", name: "Infernal Beast", family: "Demon",
            minLevel: 50, maxLevel: nil, rarity: .elite,
            spriteAsset: "rpg_monster_infernal_beast", idleStyle: .stomp, attackStyle: .stomp,
            threat: 10, behaviorText: "The training grounds' final examiner."
        ),
    ]

    private static let byID = Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })

    static func monster(id: String) -> RPGMonster? { byID[id] }
}
