#!/usr/bin/env python3
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "docs" / "repsetforge-tokens.json"
OUTPUT = ROOT / "RepSetForge" / "Design" / "DesignTokens.swift"


def swift_name(name):
    return re.sub(r"[^A-Za-z0-9_]", "", name)


def color_components(value):
    if value.startswith("#"):
        value = value[1:]
        return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16), 1.0
    match = re.fullmatch(r"rgba\((\d+),(\d+),(\d+),([0-9.]+)\)", value)
    if match:
        return int(match.group(1)), int(match.group(2)), int(match.group(3)), float(match.group(4))
    raise ValueError(f"Unsupported color: {value}")


def color_literal(value):
    red, green, blue, alpha = color_components(value)
    return (
        f"Color(red: {red}/255, green: {green}/255, blue: {blue}/255, opacity: {alpha:g})"
    )


def swift_weight(value):
    weights = {
        500: "medium",
        600: "semibold",
        700: "bold",
        800: "heavy",
    }
    return weights.get(value, "regular")


def main():
    data = json.loads(TOKENS.read_text())
    dark = data["color"]["dark"]
    light = data["color"]["light"]
    typography = data["typography"]["scale"]
    spacing = data["spacing"]
    radius = data["radius"]
    motion = data["motion"]

    lines = [
        "// Generated by Scripts/generate_design_tokens.py from docs/repsetforge-tokens.json.",
        "// Do not edit by hand.",
        "",
        "import SwiftUI",
        "",
        "enum DesignTokens {",
        "  enum ColorToken {",
    ]

    for key in dark:
        lines += [
            f"    static let {swift_name(key)} = Color(light: {color_literal(light[key])}, dark: {color_literal(dark[key])})"
        ]

    lines += [
        "  }",
        "",
        "  enum Typography {",
    ]

    for key, value in typography.items():
        size = value["size"]
        weight = value["weight"]
        tracking = value.get("tracking", 0)
        lines += [
            f"    static let {swift_name(key)} = TextStyle(size: {size}, weight: .{swift_weight(weight)}, tracking: {tracking})"
        ]

    lines += [
        "  }",
        "",
        "  enum Spacing {",
        f"    static let base: CGFloat = {spacing['base']}",
        f"    static let screenGutter: CGFloat = {spacing['screenGutter']}",
        f"    static let cardPadding: CGFloat = {spacing['cardPadding']}",
        f"    static let cardGap: CGFloat = {spacing['cardGap']}",
        f"    static let setRowHeightVisual: CGFloat = {spacing['setRowHeightVisual']}",
        f"    static let setRowHitTarget: CGFloat = {spacing['setRowHitTarget']}",
    ]
    for index, step in enumerate(spacing["steps"], start=1):
        lines.append(f"    static let step{index}: CGFloat = {step}")

    lines += [
        "  }",
        "",
        "  enum Radius {",
    ]
    for key, value in radius.items():
        lines.append(f"    static let {swift_name(key)}: CGFloat = {value}")

    lines += [
        "  }",
        "",
        "  enum Motion {",
        f"    static let setCompleteDuration: TimeInterval = {motion['setComplete']['duration'] / 1000:g}",
        f"    static let stateChangeDuration: TimeInterval = {motion['stateChange']['duration'] / 1000:g}",
        "  }",
        "}",
        "",
        "extension Color {",
        "  init(light: Color, dark: Color) {",
        "    self.init(uiColor: UIColor { traits in",
        "      traits.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)",
        "    })",
        "  }",
        "}",
        "",
        "struct TextStyle {",
        "  let size: CGFloat",
        "  let weight: Font.Weight",
        "  let tracking: CGFloat",
        "",
        "  var font: Font {",
        "    .system(size: size, weight: weight, design: .monospaced)",
        "  }",
        "}",
        "",
        "extension View {",
        "  func forgeTextStyle(_ style: TextStyle) -> some View {",
        "    font(style.font)",
        "      .tracking(style.tracking)",
        "  }",
        "",
        "  func forgeNumeric() -> some View {",
        "    monospacedDigit()",
        "  }",
        "}",
    ]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
